name: Build

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
