name: Build

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ruleset_converter
        run: wget https://github.com/bromite/bromite/releases/download/102.0.5005.67/ruleset_converter -P tmp -O output.txt --no-verbose
      - name: Download lists
        run: wget -i filters.txt -P tmp --no-verbose
      - name: Convert lists
        run: tmp/ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset --input_files=tmp/filters.txt --output_file=tmp/filters.dat
