name: Build

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ruleset_converter
        run: wget https://github.com/bromite/bromite/releases/download/102.0.5005.67/ruleset_converter --no-verbose && chmod +x ruleset_converter
      - name: Download lists
        run: wget -i lists.txt -O filters.txt --no-verbose
      - name: Convert lists
        run: ./ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset --input_files=filters.txt --output_file=filters.dat
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Filters
          path: filters.dat
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
