name: Build

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ruleset_converter
        run: curl https://github.com/bromite/bromite/releases/download/102.0.5005.67/ruleset_converter -o ruleset_converter
